In [1]:
import numpy as np
import pandas as pd
#import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_frame = pd.read_csv("diabetes database.csv")
data_frame.head(5)

Pregnancies  Glucose(mg/dl)  BloodPressure (mmHg)  SkinThickness(mm)  \
0            6             148                    72                 35   
1            1              85                    66                 29   
2            8             183                    64                  0   
3            1              89                    66                 23   
4            0             137                    40                 35   

   Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  
0        0  33.6                     0.627   50        1  
1        0  26.6                     0.351   31        0  
2        0  23.3                     0.672   32        1  
3       94  28.1                     0.167   21        0  
4      168  43.1                     2.288   33        1

In [3]:
data_frame.tail(5)

Pregnancies  Glucose(mg/dl)  BloodPressure (mmHg)  SkinThickness(mm)  \
763           10             101                    76                 48   
764            2             122                    70                 27   
765            5             121                    72                 23   
766            1             126                    60                  0   
767            1              93                    70                 31   

     Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  
763      180  32.9                     0.171   63        0  
764        0  36.8                     0.340   27        0  
765      112  26.2                     0.245   30        0  
766        0  30.1                     0.349   47        1  
767        0  30.4                     0.315   23        0

In [4]:
print (data_frame.isnull().values.any())

False


In [5]:
diabetes_map = {True : 1, False : 0}
data_frame['Outcome'] = data_frame['Outcome'].map(diabetes_map)
data_frame.head(5)

Pregnancies  Glucose(mg/dl)  BloodPressure (mmHg)  SkinThickness(mm)  \
0            6             148                    72                 35   
1            1              85                    66                 29   
2            8             183                    64                  0   
3            1              89                    66                 23   
4            0             137                    40                 35   

   Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  
0        0  33.6                     0.627   50        1  
1        0  26.6                     0.351   31        0  
2        0  23.3                     0.672   32        1  
3       94  28.1                     0.167   21        0  
4      168  43.1                     2.288   33        1

In [6]:
num_obs = len(data_frame)
num_true = len(data_frame.loc[data_frame['Outcome'] == 1])
num_false = len(data_frame.loc[data_frame['Outcome'] == 0])
print("Number of True cases:  {0} ({1:2.2f}%)".format(num_true, ((1.00 * num_true)/(1.0 * num_obs)) * 100))
print("Number of False cases: {0} ({1:2.2f}%)".format(num_false, (( 1.0 * num_false)/(1.0 * num_obs)) * 100))
from sklearn.model_selection import train_test_split

feature_col_names = ['Pregnancies', 'Glucose(mg/dl)', 'BloodPressure (mmHg)', 'SkinThickness(mm)', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
predicted_class_names = ['Outcome']

X = data_frame[feature_col_names].values     # predictor feature columns (8 X m)
y = data_frame[predicted_class_names].values # predicted class (1=true, 0=false) column (1 X m)
split_test_size = 0.30

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split_test_size, random_state=42) 
                            # test_size = 0.3 is 30%, 42 is the answer to everything
trainval = (1.0 * len(X_train)) / (1.0 * len(data_frame.index))
testval = (1.0 * len(X_test)) / (1.0 * len(data_frame.index))
print("{0:0.2f}% in training set".format(trainval * 100))
print("{0:0.2f}% in test set".format(testval * 100))
print("Original True  : {0} ({1:0.2f}%)".format(len(data_frame.loc[data_frame['Outcome'] == 1]), (len(data_frame.loc[data_frame['Outcome'] == 1])/len(data_frame.index)) * 100.0))
print("Original False : {0} ({1:0.2f}%)".format(len(data_frame.loc[data_frame['Outcome'] == 0]), (len(data_frame.loc[data_frame['Outcome'] == 0])/len(data_frame.index)) * 100.0))
print("")
print("Training True  : {0} ({1:0.2f}%)".format(len(y_train[y_train[:] == 1]), (len(y_train[y_train[:] == 1])/len(y_train) * 100.0)))
print("Training False : {0} ({1:0.2f}%)".format(len(y_train[y_train[:] == 0]), (len(y_train[y_train[:] == 0])/len(y_train) * 100.0)))
print("")
print("Test True      : {0} ({1:0.2f}%)".format(len(y_test[y_test[:] == 1]), (len(y_test[y_test[:] == 1])/len(y_test) * 100.0)))
print("Test False     : {0} ({1:0.2f}%)".format(len(y_test[y_test[:] == 0]), (len(y_test[y_test[:] == 0])/len(y_test) * 100.0)))


Number of True cases:  268 (34.90%)
Number of False cases: 500 (65.10%)
69.92% in training set
30.08% in test set
Original True  : 268 (34.90%)
Original False : 500 (65.10%)

Training True  : 188 (35.01%)
Training False : 349 (64.99%)

Test True      : 80 (34.63%)
Test False     : 151 (65.37%)


In [7]:
print("# rows in dataframe {0}".format(len(data_frame)))
print("# rows missing glucose_conc: {0}".format(len(data_frame.loc[data_frame['Glucose(mg/dl)'] == 0])))
print("# rows missing diastolic_bp: {0}".format(len(data_frame.loc[data_frame['BloodPressure (mmHg)'] == 0])))
print("# rows missing thickness: {0}".format(len(data_frame.loc[data_frame['SkinThickness(mm)'] == 0])))
print("# rows missing insulin: {0}".format(len(data_frame.loc[data_frame['Insulin'] == 0])))
print("# rows missing bmi: {0}".format(len(data_frame.loc[data_frame['BMI'] == 0])))
print("# rows missing diab_pred: {0}".format(len(data_frame.loc[data_frame['DiabetesPedigreeFunction'] == 0])))
print("# rows missing age: {0}".format(len(data_frame.loc[data_frame['Age'] == 0])))

# rows in dataframe 768
# rows missing glucose_conc: 5
# rows missing diastolic_bp: 35
# rows missing thickness: 227
# rows missing insulin: 374
# rows missing bmi: 11
# rows missing diab_pred: 0
# rows missing age: 0


In [63]:
from sklearn.impute import SimpleImputer

#Impute with mean all 0 readings

fill_0 = SimpleImputer(missing_values=0, strategy="mean")

X_train = fill_0.fit_transform(X_train)
X_test = fill_0.fit_transform(X_test)
from sklearn.tree import DecisionTreeClassifier
print("decision tree")
dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train.ravel())
prediction_from_trained_data = dt_model.predict(X_train)
from sklearn import metrics

accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Accuracy of our DT modelon trained data is : {0:.4f}".format(accuracy))
dt_predict_test = dt_model.predict(X_test)

#get accuracy
dt_accuracy_testdata = metrics.accuracy_score(y_test, dt_predict_test)

#print accuracy
print ("Accuracy of DT model on test data: {0:.4f}".format(dt_accuracy_testdata))
import matplotlib as plot

print ("Confusion Matrix for DT")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.confusion_matrix(y_test, dt_predict_test, labels=[1, 0])))

print ("")

print ("Classification Report\n")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.classification_report(y_test, dt_predict_test, labels=[ 1,0])))

decision tree
Accuracy of our DT modelon trained data is : 1.0000
Accuracy of DT model on test data: 0.7143
Confusion Matrix for DT
[[ 52  28]
 [ 38 113]]

Classification Report

              precision    recall  f1-score   support

           1       0.58      0.65      0.61        80
           0       0.80      0.75      0.77       151

    accuracy                           0.71       231
   macro avg       0.69      0.70      0.69       231
weighted avg       0.72      0.71      0.72       231



In [64]:
from sklearn.naive_bayes import GaussianNB
print("naive bayes")
# create Gaussian Naive Bayes model object and train it with the data
nb_model = GaussianNB()

nb_model.fit(X_train, y_train.ravel())
prediction_from_trained_data = nb_model.predict(X_train)
from sklearn import metrics

accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Accuracy of our naive bayes model on training data is : {0:.4f}".format(accuracy))
prediction_from_test_data = nb_model.predict(X_test)

accuracy = metrics.accuracy_score(y_test, prediction_from_test_data)

print ("Accuracy of our naive bayes model is: {0:0.4f}".format(accuracy))
print ("Confusion Matrix")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.confusion_matrix(y_test, prediction_from_test_data, labels=[1, 0])))
print ("Classification Report")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.classification_report(y_test, prediction_from_test_data, labels=[1, 0])))

naive bayes
Accuracy of our naive bayes model on training data is : 0.7542
Accuracy of our naive bayes model is: 0.7359
Confusion Matrix
[[ 52  28]
 [ 33 118]]
Classification Report
              precision    recall  f1-score   support

           1       0.61      0.65      0.63        80
           0       0.81      0.78      0.79       151

    accuracy                           0.74       231
   macro avg       0.71      0.72      0.71       231
weighted avg       0.74      0.74      0.74       231



In [65]:
from sklearn.linear_model import LogisticRegressionCV
lr_cv_model = LogisticRegressionCV(n_jobs=-1, random_state=42, Cs=3, cv=10, refit=False, class_weight="balanced")  

# set number of jobs to -1 which uses all cores to parallelize
lr_cv_model.fit(X_train, y_train.ravel())

lr_cv_predict_test = lr_cv_model.predict(X_test)

# training metrics
print( "Accuracy of Logistic Regression: {0:.4f}".format(metrics.accuracy_score(y_test, lr_cv_predict_test)))
print (metrics.confusion_matrix(y_test, lr_cv_predict_test, labels=[1, 0])) 
print ("")
print ("Classification Report")
print (metrics.classification_report(y_test, lr_cv_predict_test, labels=[1,0]))

Accuracy of Logistic Regression: 0.7056
[[ 54  26]
 [ 42 109]]

Classification Report
              precision    recall  f1-score   support

           1       0.56      0.68      0.61        80
           0       0.81      0.72      0.76       151

    accuracy                           0.71       231
   macro avg       0.68      0.70      0.69       231
weighted avg       0.72      0.71      0.71       231



In [66]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear', C=1, random_state=42)

svm_model.fit(X_train, y_train.ravel())
prediction_from_trained_data = svm_model.predict(X_train)
from sklearn import metrics

accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Accuracy of our SVM model on trained data is : {0:.4f}".format(accuracy))
svm_predict_test = svm_model.predict(X_test)

#get accuracy
svm_accuracy_testdata = metrics.accuracy_score(y_test, svm_predict_test)

#print accuracy
print ("Accuracy of SVM model on tested data: {0:.4f}".format(svm_accuracy_testdata))
import matplotlib as plot

print ("Confusion Matrix for Support Vector machine")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.confusion_matrix(y_test, svm_predict_test, labels=[1, 0])))

print ("")

print ("Classification Report\n")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.classification_report(y_test, svm_predict_test, labels=[1, 0])))

Accuracy of our SVM model on trained data is : 0.7840
Accuracy of SVM model on tested data: 0.7359
Confusion Matrix for Support Vector machine
[[ 46  34]
 [ 27 124]]

Classification Report

              precision    recall  f1-score   support

           1       0.63      0.57      0.60        80
           0       0.78      0.82      0.80       151

    accuracy                           0.74       231
   macro avg       0.71      0.70      0.70       231
weighted avg       0.73      0.74      0.73       231



In [67]:
from sklearn.neural_network import MLPClassifier
ann_model = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500, random_state=42)

ann_model.fit(X_train, y_train.ravel())
prediction_from_trained_data = ann_model.predict(X_train)
from sklearn import metrics

accuracy = metrics.accuracy_score(y_train, prediction_from_trained_data)

print ("Accuracy of our ANN model on trained model is : {0:.4f}".format(accuracy))

ann_predict_test = ann_model.predict(X_test)

#get accuracy
ann_accuracy_testdata = metrics.accuracy_score(y_test, ann_predict_test)

#print accuracy
print ("Accuracy of our ANN model on test data: {0:.4f}".format(ann_accuracy_testdata))
import matplotlib as plot
print ("Confusion Matrix for Artificial Neural Network")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.confusion_matrix(y_test, ann_predict_test, labels=[1, 0])))

print ("")

print ("Classification Report\n")

# labels for set 1=True to upper left and 0 = False to lower right
print ("{0}".format(metrics.classification_report(y_test, ann_predict_test, labels=[ 1,0])))

Accuracy of our ANN model on trained model is : 0.8045
Accuracy of our ANN model on test data: 0.7013
Confusion Matrix for Artificial Neural Network
[[ 40  40]
 [ 29 122]]

Classification Report

              precision    recall  f1-score   support

           1       0.58      0.50      0.54        80
           0       0.75      0.81      0.78       151

    accuracy                           0.70       231
   macro avg       0.67      0.65      0.66       231
weighted avg       0.69      0.70      0.70       231



In [41]:
X=data_frame.drop('Outcome',axis=1)
y=data_frame['Outcome']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=0)
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials
space = {'criterion': hp.choice('criterion', ['entropy', 'gini']),
        'max_depth': hp.quniform('max_depth', 10, 1200, 10),
        'max_features': hp.choice('max_features', ['auto', 'sqrt','log2', None]),
        'min_samples_leaf': hp.uniform('min_samples_leaf', 0, 0.5),
        'min_samples_split' : hp.uniform ('min_samples_split', 0, 1),
        'n_estimators' : hp.choice('n_estimators', [10, 50, 300, 750, 1200,1300,1500])
    }
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
def objective(space):
    model = RandomForestClassifier(criterion = space['criterion'], max_depth = space['max_depth'],
                                 max_features = space['max_features'],
                                 min_samples_leaf = space['min_samples_leaf'],
                                 min_samples_split = space['min_samples_split'],
                                 n_estimators = space['n_estimators'], 
                                 )
    
    accuracy = cross_val_score(model, X_train, y_train, cv = 5).mean()

    # We aim to maximize accuracy, therefore we return it as a negative value
    return {'loss': -accuracy, 'status': STATUS_OK }
from sklearn.model_selection import cross_val_score
trials = Trials()
best = fmin(fn= objective,
            space= space,
            algo= tpe.suggest,
            max_evals = 80,
            trials= trials)
best
crit = {0: 'entropy', 1: 'gini'}
feat = {0: 'auto', 1: 'sqrt', 2: 'log2', 3: None}
est = {0: 10, 1: 50, 2: 300, 3: 750, 4: 1200,5:1300,6:1500}


print(crit[best['criterion']])
print(feat[best['max_features']])
print(est[best['n_estimators']])
trainedforest = RandomForestClassifier(criterion = crit[best['criterion']], max_depth = best['max_depth'], 
                                       max_features = feat[best['max_features']], 
                                       min_samples_leaf = best['min_samples_leaf'], 
                                       min_samples_split = best['min_samples_split'], 
                                       n_estimators = est[best['n_estimators']]).fit(X_train,y_train)
predictionforest = trainedforest.predict(X_test)

print('---------------------- confusion_matrix -------------------------')
print(confusion_matrix(y_test,predictionforest))

print('---------------------- accuracy_score -------------------------')
print(accuracy_score(y_test,predictionforest))

print('---------------------- classification_report -------------------------')
print(classification_report(y_test,predictionforest))
acc5 = accuracy_score(y_test,predictionforest)

100%|███████████████████████████████████████████████| 80/80 [11:13<00:00,  8.42s/trial, best loss: -0.7583984985924304]
gini
log2
300
---------------------- confusion_matrix -------------------------
[[46  5]
 [ 9 17]]
---------------------- accuracy_score -------------------------
0.8181818181818182
---------------------- classification_report -------------------------
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        51
           1       0.77      0.65      0.71        26

    accuracy                           0.82        77
   macro avg       0.80      0.78      0.79        77
weighted avg       0.81      0.82      0.81        77

